name: ci-cd

on:
  pull_request:
    branches: [ master, dev ]
  push:
    branches: [ master, dev ] 

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}
  MODE: dev

jobs:
  tests:
    name: Lint Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: lint check
        run: npm run lint -- --no-fix
        continue-on-error: false

  build-push:
    if: github.event_name == 'push'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.MODE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/*"
          target: "/srv/cardgame/frontend/${{ env.MODE }}"
          strip_components: 1

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/cardgame/frontend/${{ env.MODE }}
            
            export REGISTRY=${{ env.REGISTRY }}
            export FRONTEND_IMAGE_NAME=${{ env.FRONTEND_IMAGE_NAME }}
            export MODE=${{ env.MODE }}
            export DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            
            echo "${{ github.token }}" | docker login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.MODE }}
            
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose up -d
            
            for image in $(docker images | grep none | awk '{print $3}' | cat); do docker rmi "$image"; done